# Настройка ОС: hostname, DNS, NTP и т.д.
- import_tasks: os.yml
  become: yes
  tags:
    - origin_os

# Установка софта
- import_tasks: soft.yml
  become: yes
  tags:
    - origin_soft

# Создание и настройка пользователей
- name: "Get OS group list"
  shell: "cat /etc/group | awk -F':' '{print $1}'"
  register: ugroup_raw
  changed_when: false

- name: "Define system groups array"
  set_fact:
    ugroups: "{{ ugroup_raw.stdout_lines }}"

- block:
    - include_tasks: user.yml
      loop: "{{ users }}"
      loop_control:
        loop_var: user
      tags:
        - origin_user
  become: true
